export const articles = [
    {
        id: 1,
        imgSrc: 'images/quigon.jpg',
        imgAlt: 'Qui-Gon Jinn',
        name: 'Qui-Gon Jinn',
        info: 'He was a wise and well-respected Jedi who followed his own path and strove to follow the will of the force. He was known for discovering the chosen one as young Anakin Skywalker on Tatooine.',
        birth: '80BBY, Coruscant',
        death: '32BBY, Naboo',
        species: 'Human',
        master: 'Count Dooku',
        padawan: 'Obi-Wan Kenobi',
        rank: 'Jedi Master',
        lightsaber: 'green',
        midochlorians: '17,500',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        tcw: 'The Clone Wars(2008-2020)',
        owk: 'Obi-Wan Kenobi(2022)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Jedi Master", "Green", "Human"]
    },
    {
        id: 2,
        imgSrc: 'images/obiwan.jpeg', 
        imgAlt: 'Obi-Wan Kenobi',
        name: 'Obi-Wan Kenobi',
        info: 'He was a skilled, powerfuly, and an overly polite Jedi who was always willing to face his own problems. He trained Anakin Skywalker at the request of Qui-Gon Jinn before dying.',
        info2: 'He played a very big role in the Clone Wars as a High Jedi General and managed to survive Order 66, where he went into hiding until he was ready to become a Jedi.',
        birth: '57BBY, Stewion',
        death: '0 ABY, Death Star',
        species: 'Human',
        master: 'Qui-Gon Jinn',
        padawan: 'Anakin Skywalker, Luke Skywalker',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '13,400',
        council: '21-19BBY, replaced Depa Billaba',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor (19BBY-0ABY)',
        survivor_info: 'He was on Utapau during Order 66. He was transversing up a cliff on a reptilian mount, and was blasted into a river and managed to escape.',
        alliance: 'Rebel Alliance (0ABY)',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        swjfo: 'Star Wars Jedi: Fallen Order (2019)',
        owk: 'Obi-Wan Kenobi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        totj: 'Tales of the Jedi(2022)',
        anh: 'Star Wars IV: A New Hope(1977)',
        tesb: 'Star Wars V: The Empire Strikes Back(1980)',
        rotj: 'Star Wars VI: Return of the Jedi(1983)',
        tfa: 'Star Wars VII: The Force Awakens(2015)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Jedi Master", "Blue", "Human", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Order 66 Survivors", "Rebel Alliance"]
    },
    {
        id: 3,
        imgSrc: 'images/anakin.jpg',
        imgAlt: 'Anakin Skywalker',
        name: 'Anakin Skywalker',
        info: 'He was considered one of the strongest Jedi in the Jedi Order. He was compassionate and caring hero of the Clone Wars, but was also considered arrogant, reckless, and impatient in certain situations. He was belived to be the Chosen One, the one who was bring balance to the Force. As a Jedi however, he married former Queen Padme Amidala, which was forbidden to the Jedi Order, and was forced to keep it secret. After having visions of Padme dying in childbirth, he turned to Palpatine(Darth Sidious) and became his new apprentice known as Darth Vader. He was responsible for the death of almost all the Jedi, allowing the rise of the Empire.',
        birth: '41 BBY, Tatooine',
        death: '4 ABY, Death Star',
        species: 'Human',
        family: 'Family',
        parents: 'Shmi Skywalker, Cliegg Lars(step-father)',
        spouse: 'Padme Amidala',
        siblings: 'Owen Lars, Beru(sister-in-law)',
        children: 'Luke Skywalker, Leia Organa',
        master: 'Obi-Wan Kenobi',
        padawan: 'Ahsoka Tano',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        midochlorians: '27,000',
        war: 'Clone Wars',
        council: '19BBY, replaced Oppo Rancisis',
        sith: 'Darth Vader, 19BBY-4ABY',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        swjfo: 'Star Wars Jedi: Fallen Order (2019)',
        swjs: 'Star Wars Jedi: Survivor (2023)',
        owk: 'Obi-Wan Kenobi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        totj: 'Tales of the Jedi(2022)',
        tote: 'Tales of the Empire(2024)',
        ro: 'Rogue One: A Star Wars Story(2016)',
        anh: 'Star Wars IV: A New Hope(1977)',
        tesb: 'Star Wars V: The Empire Strikes Back(1980)',
        rotj: 'Star Wars VI: Return of the Jedi(1983)',
        ahsoka: 'Ahsoka(2023)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Jedi Knight", "Blue", "Red", "Human", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Sith"]

    },
    {
        id: 4,
        imgSrc: 'images/Quinlan_Vos.jpeg',
        imgAlt: 'Quinlan Vos',
        name: 'Quinlan Vos',
        birth: '57BBY',
        species:'Kiffar',
        master: 'Tholme, Count Dooku',
        padawan: 'Aayla Secura',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Kiffar", "Jedi Master", "Green", "Red", "Clone Wars", "Order 66 Survivors", "Sith"]

    },
    {
        id: 5,
        imgSrc: 'images/yoda.jpeg',
        imgAlt: 'Yoda',
        name: 'Yoda',
        info: 'Yoda was one of the oldest members and the Grand Master of the Jedi Council. He was the most intelligent and wise Jedi in the galaxy. For 800 years, he trained many generatiions of Jedi until the rise of the Empire. Though very old, he is strong and powerful in the force, so much so, he survived Order 66 and battled Darth Sidious. Afterwards, he went into hiding on Dagobah where he would train Luke Skywalker before dying of old age.',
        birth: '896 BBY',
        death: '4 ABY, Dagobah',
        species: 'Yoda Species',
        padawan: 'Count Dooku, Mace Windu, Ki-Adi Mundi, Obi-Wan Kenobi, Cin Drallig, Anakin Skywalker, Luke Skywalker',
        rank: 'Grand Master',
        lightsaber: 'green',
        midochlorians: '16,900',
        council: '382-19BBY',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19BBY-4ABY)',
        survivor_info: 'He was in Kashyyk during Order 66. He sensed the disturbance in the Force, and killed the Clone Commanders who were about to gun him down. He then managaed to escape with the help of the Wookies, Chewbacca and Tarrful.',
        ta: 'The Acolyte(2024)',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',  
        rots: 'Star Wars III: Revenge of the Sith(2005)',    
        totj: 'Tales of the Jedi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        tesb: 'Star Wars V: The Empire Strikes Back(1980)',
        rotj: 'Star Wars VI: Return of the Jedi(1983)',
        tlj: 'Star Wars VIII: The Last Jedi(2017)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Yoda Species","Grand Master", "Green", "High Republic", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Order 66 Survivors"]

    },
    {
        id: 6,
        imgSrc: 'images/Mace_Windu.PNG',
        imgAlt: 'Mace_Windu',
        name: 'Mace Windu',
        info: 'He was a very powerful Jedi who was incredibly compassionate and brave, willing to risk life and limb many times to protect the people of the Repulic. He was one of the few Jedi who held a purple lightsaber, because he was rash and reckless with his decisions, leading to his demise.',
        birth: '72BBY, Haruun Kai',
        death: '19BBY, Coruscant',
        species: 'Human',
        master: 'Yoda',
        padawan: 'Depa Billaba',
        rank: 'Jedi Master',
        lightsaber: 'purple',
        midochlorians: '12,000',
        council: '32-19BBY',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',  
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',  
        totj: 'Tales of the Jedi(2022)',     
        tags: ["Human", "Jedi Master", "Purple", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
        
    },
    {
        id: 7,
        imgSrc: 'images/Ki-Adi_Mundi.JPG',
        imgAlt: 'Ki-Adi Mundi',
        name: 'Ki-Adi Mundi',
        info: 'He was a capable and respected Jedi Master on the Jedi High Council known for his wisdom, noble thinking, and courage. He was however, emotionally unsympathetic, and arrogant.',
        birth: '92 BBY',
        death: '19BBY, Mygeeto',
        species: 'Cerean',
        Master: 'Yoda',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '13,500',
        council: '33-19 BBY',
        war: 'Clone Wars',
        ta: 'The Acolyte(2024)',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Cerean", "Jedi Master", "Blue", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 8,
        imgSrc: 'images/Plo_Koon.PNG',
        imgAlt: 'Plo Koon',
        name: 'Plo Koon',
        info: 'He was among the wisest and compassionate Jedi of the Jedi Order. He was respected for beinh a skilled pilot and his level-headed analysis of event unflappable wisdom, calmness, and dedication to the Jedi ideals.',
        birth: '400 BBY, Dorin',
        death: '19 BBY, Cato Neimoidia',
        species: 'Kel Dor',
        padawan: 'Butlar Swan',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '12,800',
        council: '33-19 BBY',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Kel Dor", "Jedi Master", "Blue", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
        
    },
    {
        id: 9,
        imgSrc: 'images/Saesse_Tinn.jpeg',
        imgAlt: 'Saesse Tinn',
        name: 'Saesse Tinn',
        info: 'He was a member of the Jedi High Council who had natural telepathic powers, and was therefore a skilled courageous master of lightsaber and a capable starfighter pilot.',
        death: '19BBY, Coruscant',
        species: 'Iktotchi',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '40-19 BBY',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Iktotchi", "Jedi Master", "Green", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 10,
        imgSrc: 'images/Yaddle.jpeg',
        imgAlt: 'Yaddle',
        name: 'Yaddle',
        info: 'She was a powerful, yet subtle Jedi known for her wisdom, compassion, and quiet demeanor.',
        birth: '509BBY',
        death: '32BBY, Coruscant',
        species: 'Yoda Species',
        padawan: 'Oppo Rancisis, Jarol Tapal',
        rank: 'Jedi Master',
        lightsaber: 'green',
        midochlorians: '13,817',
        council: '-32BBY',
        tpm: 'Star Wars I: The Phantom Menace(1999)',

        tags: [ "Jedi Master", "Green", "Jedi High Council"]
    },
    {
        id: 11,
        imgSrc: 'images/Even_Piell.jpeg',
        imgAlt: 'Even Piell',
        name: 'Even Piell',
        info: 'He was a gruff and battle-hardened Jedi and a great warrior who was bigger than life though small in stature and was always willing to charge into battle.',
        death: '20BBY, Lola Sayu',
        species: 'Lannik',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '33-20BBY, replaced by Coleman Kcaj',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Lannik", "Jedi Master", "Green", "Jedi High Council", "Clone Wars"]
    },
    {
        id: 12,
        imgSrc: 'images/Oppo_Rancisis.JPG',
        imgAlt: 'Oppo Rancisis', 
        name: 'Oppo Rancisis',
        species: 'Thisspiasian',
        master: 'Yaddle',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '232-19BBY',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Thisspiasian", "Jedi Master", "Green", "High Republic","Jedi High Council", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 13,
        imgSrc: 'images/Ada_Gallia.jpeg',
        imgAlt: 'Ada Gallia',
        name: 'Ada Gallia',
        info: 'She was a stern and focused Jedi and Aggressive Warrior known for her skills as a diplomat and political consultant.',
        death: '19BBY, Florrum',
        species: 'Tholothian',
        family: 'Family',
        cousin: 'Stass Allie',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        council: '32-19BBY, replaced by Stass Allie',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Tholothian", "Jedi Master", "Blue", "Jedi High Council", "Clone Wars"]
    },
    {
        id: 14,
        imgSrc: 'images/Yarael_Poof.jpeg',
        imgAlt: 'Yarael Poof',
        name: 'Yarael Poof',
        info: 'A Quermian Jedi who was on the Jedi High Council during the Phantom Menace and before Attack of the Clones.',
        death: '22BBY',
        species: "Quermian",
        rank: 'Jedi Master',
        lightsaber: 'blue',
        council: '232-22BBY',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        tags: ["Quermian", "Jedi Master", "Blue","High Republic", "Jedi High Council"]
    },
    {
        id: 15,
        imgSrc: 'images/Eeth_Koth.jpeg',
        imgAlt: 'Eeth Koth',
        name: 'Eeth Koth',
        death: '14BBY',
        species: 'Zabrak',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '40-21BBY',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19-14BBY)',
        survivor_info: 'He left the Jedi Order during the Clone Wars and settled down to have a family.',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tcw: 'The Clone Wars (2008-2020)',
        totj: 'Tales of the Jedi (2022)',
        tags: ["Zabrak", "Jedi Master", "Green", "Jedi High Council", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 16,
        imgSrc: 'images/Depa_Billaba.JPG',
        imgAlt: 'Depa Billaba',
        name: 'Depa Billaba',
        death: '19BBY, Kaller',
        species: 'Chalactan',
        master: 'Mace Windu',
        padawan: 'Kanan Jarrus',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '40-21BBY',
        war: 'Clone Wars',
        tpm: 'Star Wars I: The Phantom Menace(1999)',
        aotc: 'Star Wars II: Attack of the Clones(2002)', 
        tbb: 'The Bad Batch(2021-2024)',
        tags: ["Chalactan", "Jedi Master", "Green", "Jedi High Council", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 17,
        imgSrc: 'images/Kit_Fisto.jpeg',
        imgAlt: 'Kit Fisto',
        name: 'Kit Fisto',
        death: '19BBY, Coruscant',
        species: 'Nautolan',
        padawan:'Nahdar Vebb',
        rank: 'Jedi Master',
        lightsaber: 'green',
        midochlorians: '17,300',
        war: 'Clone Wars',
        council: '22-19BBY, replaced Coleman Trebor',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Nautolan", "Jedi Master", "Green", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 18,
        imgSrc: 'images/Luminara.jpeg',
        imgAlt: 'Luminara Unduli',
        name: 'Luminara Unduli',
        death: '19BBY',
        species: 'Mirialan',
        padawan: 'Barris Offee',
        rank: 'Jedi Master',
        lightsaber: 'green',
        midochlorians: '16,200',
        war: 'Clone Wars',
        survivor: 'Order 66 Suvivor(19BBY)',
        survivor_info: 'She was in Kashyyk during Order 66 and while she avoided death, she was eventually captured by the Empire where she was killed by the Grand Inquisitor. Her remains lured other Jedi to their demise.',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        swr: 'Star Wars Rebels(2014-2018)',
        tags: ["Mirialan", "Jedi Master", "Green", "Genosis Strike Team", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 19,
        imgSrc: 'images/Barris_Offee.jpg',
        imgAlt: 'Barris Offee',
        name: 'Barris Offee',
        birth: '40BBY',
        species: 'Mirialan',
        master: 'Luminara Unduli',
        rank: 'Padawan',
        lightsaber: 'blue',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        survivor_info: 'She was imprisoned during Order 66, but she was eventually appointed to be an inquistor of Darth Vader.',
        sith: 'Inquisitor',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        tote: 'Tales of the Empire(2024)',
        tags: ["Mirialan", "Padawan", "Blue", "Red", "Clone Wars", "Order 66 Survivors", "Sith"]
    },
    {
        id: 20,
        imgSrc: 'images/Shaak_Ti.jpeg',
        imgAlt: 'Shaak Ti',
        name: 'Shaak Ti',
        death: '19BBY',
        species: 'Togruta',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '15,300',
        council: '32-19BBY, replaced Yaddle',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Togruta", "Jedi Master", "Blue", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 21,
        imgSrc: 'images/Coleman_Trebor.jpeg',
        imgAlt: 'Coleman Trebor',
        name: 'Coleman Trebor',
        death: '22BBY, Genosis',
        species: 'Vurk',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '23-22BBY, replaced Yarael Poof, replaced by Kit Fisto',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Vurk", "Jedi Master", "Green", "Jedi High Council", "Genosis Strike Team", "Clone Wars"]
    },

    {
        id: 22,
        imgSrc: 'images/Jocasta_Nu.jpg',
        imgAlt: 'Jocasta Nu',
        name: 'Jocasta Nu',
        death: '19BBY, Coruscant',
        species: 'Human',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19BBY)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Human", "Jedi Master", "Blue", "Clone Wars", "Order 66 Survivors"]
    },

    {
        id: 23,
        imgSrc: 'images/Zett_Jukassa.jpg',
        imgAlt: 'Zett Jukassa',
        name: 'Zett Jukassa',
        death: '19BBY, Coruscant',
        rank: 'Padawan',
        lightsaber: 'blue',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Human", "Padawan", "Blue", "Victim of Order 66"]
    },
    {
        id: 24,
        imgSrc: 'images/Aayla_Secura.jpg',
        imgAlt: 'Aayla Secura',
        name: 'Aayla Secura',
        birth: '48BBY, Ryloth',
        death: '19BBY, Felucia',
        species: "Twi'lek",
        master: 'Quinlan Vos',
        padawan: 'Tutso Mara',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '10,000',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Twi'lek", "Jedi Master", "Blue", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 25,
        imgSrc: 'images/Sifo-Dyas.jpg',
        imgAlt: 'Sifo-Dyas',
        name: 'Sifo-Dyas',
        birth: '102BBY, Minashee',
        death: '32BBY, over the Oba Diah moon',
        species: 'Human',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        council: '39-before 32BBY',
        aotc: 'Attack of the Clones(2002), mentioned',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Human", "Jedi Master", "Blue", "Jedi High Council"]
    },
    {
        id: 26,
        imgSrc: 'images/Dooku.jpeg',
        imgAlt: 'Count Dooku',
        name: 'Count Dooku',
        birth: '102BBY, Serennoo',
        death: '19BBY, Coruscant',
        species: 'Human',
        master: 'Yoda, Darth Sidious',
        padwan: 'Qui-Gon Jinn, Asajj Ventress, Savage Oppress, Quinlan Vos, General Grievous',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        midochlorians: '16,500',
        sith: 'Darth Tyrannus',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Human", "Jedi Master", "Blue", "Red", "Sith"]

    },
    {
        id: 27,
        imgSrc: 'images/Pablo_Jill.jpeg',
        imgAlt: 'Pablo Jill',
        name: 'Pablo Jill',
        death: 'between 19-9BBY',
        species: 'Ongree',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Ongree", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 28,
        imgSrc: 'images/Agen_Kolar.jpeg',
        imgAlt: 'Agen Kolar',
        name: 'Agen Kolar',
        death: '19BBY, Coruscant',
        species: 'Zabrak',
        padawan: 'Tan Yuster',
        rank: 'Jedi Master',
        lightsaber: 'green, blue',
        council: '21-19BBY, replaced Eeth Koth',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tcw: 'The Clone Wars (2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Zabrak", "Jedi Master", "Blue", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 29,
        imgSrc: 'images/Stass_Allie.jpeg',
        imgAlt: 'Stass Allie',
        name: 'Stass Allie',
        death: '19BBY, Saleucami',
        species: 'Tholothian',
        family: 'family',
        cousin: 'Ada Gallia',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '19BBY, replaced Ada Gallia',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Tholothian", "Jedi Master", "Green", "Jedi High Council", "Genosis Strike Team", "Clone Wars", "Victim of Order 66"]
    },
    { 
        id: 30,
        imgSrc: 'images/Butlar_Swan.jpg',
        imgAlt: 'Butlar Swan',
        name: 'Butlar Swan',
        species: 'Human',
        master: 'Plo Koon',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Master", "Green", "Genosis Strike Team", "Clone Wars"]
    },

    {
        id: 31,
        imgSrc: 'images/Nicanas_Tassu.jpg',
        imgAlt: 'Nicanas Tassu',
        name: 'Nicanas Tassu',
        death: '22BBY, Genosis',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 32,
        imgSrc: 'images/Sephjet_Josall.jpg',
        imgAlt: 'Sephjet Josall',
        name: 'Sephjet Josall',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 33,
        imgSrc: 'images/Sar_Laboooda.jpg',
        imgAlt: 'Sar Laboooda',
        name: 'Sar Laboooda',
        death: '22BBY, Genosis',
        species: 'Human',
        family: 'Family',
        siblings: 'Depa Billaba',
        rank: 'Unknown',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Chalactan", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 34,
        imgSrc: 'images/Sarissa_Jeng.jpg',
        imgAlt: 'Sarissa Jeng',
        name: 'Sarissa Jeng',
        death: '22BBY, Genosis',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 35,
        imgSrc: 'images/Ekim_Ryelli.jpg',
        imgAlt: 'Ekim Ryelli',
        name: 'Ekim Ryelli',
        species: 'Human',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Master", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 36,
        imgSrc: 'images/Lumas_Etima.jpg',
        imgAlt: 'Lumas Etima',
        name: 'Lumas Etima',
        death: '22BBY, Genosis',
        species: 'Human',
        rank: 'Padawan',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
         tags: ["Human", "Padawan", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 37,
        imgSrc: 'images/Tan_Yuster.jpg',
        imgAlt: 'Tan Yuster',
        name: 'Tan Yuster',
        death: '22BBY, Genosis',
        species: 'Human',
        master: 'Agen Kolar',
        rank: 'Padawan',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Padawan", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 38,
        imgSrc: 'images/Fi-Ek_Sirch.jpg',
        imgAlt: 'Fi-Ek Sirch',
        name: 'Fi-Ek Sirch',
        death: '22BBY, Genosis',
        species: 'Nikito',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Nikitio", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 39,
        imgSrc: 'images/Que-Mars_Redath-Gom.jpg',
        name: 'Que-Mars Redath-Gom',
        death: '22BBY, Genosis',
        species: 'Weequay',
        rank: 'Jedi Knight',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Weequay", "Jedi Knight", "Green", "Genosis Strike Team", "Clone Wars"]
        
    },
    {
        id: 40,
        imgSrc: 'images/Ichi-Tan_Micoda.jpeg',
        imgAlt: 'Ichi-Tan Micoda',
        name: 'Ichi-Tan Micoda',
        death: '22BBY, Genosis',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 41,
        imgSrc: 'images/Roan_Shryne.jpg',
        imgAlt: 'Roan Shryne',
        name: 'Roan Shryne',
        death: '19BBY, Kashykk',
        species: 'Human',
        master: 'Nat-Sem',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19BBY)',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Master", "Blue", "Genosis Strike Team", "Clone Wars", 'Order 66 Survivor']
    },
    {
        id: 42,
        imgSrc: 'images/Joclad_Danva.jpg',
        imgAlt: 'Joclad Danva',
        name: 'Joclad Danva',
        death: '22BBY, Genosis',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 43,
        imgSrc: 'images/Roth-Del_Masona.jpg',
        imgAlt: 'Roth-Del Masona',
        name: 'Roth-Del Masona',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tags: ["Human", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]

    },
    {
        id: 44,
        imgSrc: 'images/Tarados_Gon.jpg',
        imgAlt: 'Tarados Gon',
        name: 'Tarados Gon',
        species: 'Klatooinian',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Klatooinian", "Jedi Knight", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 45,
        imgSrc: 'images/Sora_Bulq.jpg',
        imgAlt: 'Sora Bulq',
        name: 'Sora Bulq',
        species: 'Weequay',
        padawan: 'Galdos Stouff',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Weequay", "Jedi Master", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 46,
        imgSrc: 'images/Khaat_Qiyn.jpg',
        imgAlt: 'Khaat Qiyn',
        name: 'Khaat Qiyn',
        species: 'Human',
        padawan: 'Bairdon Jace',
        rank: 'Jedi Knight',
        lightsaber: 'green',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Jedi Knight", "Green", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 47,
        imgSrc: 'images/Bairdon_Jace.jpg',
        imgAlt: 'Bairdon Jace',
        name: 'Bairdon Jace',
        species: 'Human',
        master: 'Khaat Qiyn',
        rank: 'Padawan',
        lightsaber: 'blue',
        war: 'Clone Wars',
        aotc: 'Star Wars II: Attack of the Clones(2002)',
        tags: ["Human", "Padawan", "Blue", "Genosis Strike Team", "Clone Wars"]
    },
    {
        id: 48,
        imgSrc: 'images/Ahsoka_Tano.jpg',
        imgAlt: 'Ahsoka Tano',
        name: 'Ahsoka Tano',
        birth: '36BBY, Shuli',
        species: 'Togruta',
        master: 'Anakin Skywalker',
        padawan: 'Sabine Wren',
        rank: 'Former Jedi Padawan',
        lightsaber: 'white',
        midochlorians: '15,000',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        survivor_info: "She was returning from the Siege of Mandalore with Darth Maul during Order 66. She was able to sense Anakin's betrayal to the Jedi. When Order 66 was issued, she managed to survive thanks to Anakin's harsh trainings during the Clone Wars. She also set Darth Maul free as a distraction and learned about the inhibitor chip and managed to remove Captain Rex's chip.",
        tcw: 'The Clone Wars(2008-2020)',
        totj: 'Tales of the Jedi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        mandalorian: 'The Mandalorian(2019-2023)',
        tbobf: 'The Book of Boba Fett(2021-2022)',
        ahsoka: 'Ahsoka(2023)', 
        ros: 'Star Wars IX: Rise of Skywalker(2019)',

        tags: ["Togruta", "Padawan", "Green", "White", "Clone Wars", "Order 66 Survivors", "Rebel Alliance", "New Jedi Order"]
    },
    {
        id: 49,
        imgSrc: 'images/Asajj Ventress.jpeg',
        imgAlt: 'Asajj Ventress',
        name: 'Asajj Ventress',
        birth: '50BBY, Dathomir',
        species: 'Zarbak',
        master: 'Ky Narec, Count Dooku',
        padawan: 'Savage Oppress, Quinlan Vos',
        rank: 'Padawan',
        lightsaber: 'yellow',
        midochlorians: '12,200',
        survivor: 'Order 66 Survivor',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tbb: 'The Bad Batch(2021-2024)',
        tags: ["Human", "Padawan", "Green", "Yellow", "Red", "Sith",  "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 50,
        imgSrc: 'images/Ima-Gun_Di.jpg',
        imgAlt: 'Ima-Gun Di',
        name: 'Ima-Gun Di',
        death: '21BBY, Ryloth',
        species: 'Nikitio',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        totj: 'Tales of the Jedi(2022)',
        tags: ["Nikitio", "Jedi Master", "Blue", "Clone Wars"]

    },
    {
        id: 51,
        imgSrc: 'images/Nadhar_Vebb.jpg',
        imgAlt: 'Nadhar Vebb',
        name: 'Nadhar Vebb',
        death: '21BBY, Vassek 3',
        species: 'Mon Calamari',
        master: 'Kit Fisto',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Mon Calamari", "Jedi Knight", "Blue", "Clone Wars"]
    },
    {
        id: 52, 
        imgSrc: 'images/Bolla_Ropal.jpeg',
        imgAlt: 'Bolla Ropal',
        name: 'Bolla Ropal',
        death: '21BBY',
        species: 'Rodian',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Rodian", "Jedi Master", "Green", "Clone Wars"]
    },
    {
        id: 53,
        imgSrc: 'images/Ord_Enisence.jpeg',
        imgAlt: 'Ord Enisence',
        name: 'Ord Enisence',
        death: '22BBY',
        species: 'Skrilling',
        rank: 'Jedi Master',
        lightsaber: 'orange',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Skrilling", "Jedi Master", "Orange"]

    },
    {
        id: 54,
        imgSrc: 'images/Halsey.jpg',
        imgAlt: 'Halsey',
        name: 'Halsey',
        death: '20BBY, Sullust',
        species: 'Skrilling',
        padawan: 'Knox',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Skrilling", "Jedi Master", "Green", "Clone Wars"]
    },
    {
        id: 55,
        imgSrc: 'images/Knox.jpg',
        imgAlt: 'Knox',
        name: 'Knox',
        death: '20BBY, Sullust',
        species: 'Nautolan',
        master: 'Halsey',
        rank: 'Padawan',
        lightsaber: 'blue',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Nautolan", "Padawan", "Blue", "Clone Wars"]
    },
    {
        id: 56,
        imgSrc: 'images/Eekar_Oki.jpg',
        imgAlt: 'Eekar Oki',
        name: 'Eekar Oki',
        species: 'Mon Calamari',
        rank: 'Unknown',
        lightsaber: 'blue',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Mon Calamari", "Blue"]
    },

    {
        id: 57,
        imgSrc: 'images/Finn_Etray.jpeg',
        imgAlt: 'Finn Etray',
        name: 'Finn Etray',
        death: '19BBY, Unknown Outer Rim Spaceport',
        species: "Twi'lek",
        rank: 'Unknown',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Twi'lek", "Blue", "Clone Wars"]
    },
    {
        id: 58,
        imgSrc: 'images/Tera_Sinube.jpg',
        imgAlt: 'Tera Sinube',
        name: 'Tera Sinube',
        birth: '428BBY',
        death: '9BBY',
        species: 'Cosian',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        council: 'Eventually stepped down due to his old age',
        survivor: 'Order 66 Survivor (19-9BBY)',
        tcw: 'The Clone Wars(2008-2020)',
        totj: 'Tales of the Jedi(2022)',
        owk: 'Obi-Wan Kenobi(2022)',
        tags: ["Cosian", "Jedi Master", "Blue", "White", "Jedi High Council", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 59,
        imgSrc: 'images/Ran_Deezy.jpeg',
        imgAlt: 'Ran Deezy',
        name: 'Ran Deezy',
        species: 'Unknown',
        rank: 'Youngling',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Youngling"]    
    },
    {
        id: 60,
        imgSrc: 'images/Fran_Klin.jpeg',
        imgAlt: 'Fran Klin',
        name: 'Fran Klin',
        species: 'Unknown',
        rank: 'Youngling',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Youngling"]   
    },
    {
        id: 61,
        imgSrc: 'images/Kalifa.jpeg',
        imgAlt: 'Kalifa',
        name: 'Kalifa',
        death: '20BBY, Wasskah',
        species: 'Human',
        rank: 'Youngling',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Human", "Youngling", "Blue", "Clone Wars"]   
    },
    {
        id: 62,
        imgSrc: 'images/O-mer.jpeg',
        imgAlt: 'O-mer',
        name: 'O-mer',
        species: 'Cerean',
        rank: 'Youngling',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Cerean", "Youngling", "Clone Wars"]

    },
    {
        id: 63,
        imgSrc: 'images/Jinx.jpeg',
        imgAlt: 'Jinx',
        name: 'Jinx',
        species: "Twi'lek",
        rank: 'Youngling',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Twi'lek", "Youngling", "Clone Wars"]
    },
    {
        id: 64,
        imgSrc: 'images/Gadoni.jpeg',
        imgAlt: 'Gadoni',
        name: 'Gadoni',
        species: 'Rodian',
        rank: 'Youngling',
        lightsaber: 'green',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Rodian", "Youngling", "Green", "Clone Wars"]
    },
    {
        id: 65,
        imgSrc: 'images/Petro.jpeg',
        imgAlt: 'Petro',
        name: 'Petro',
        species: 'Human',
        rank: 'Youngling',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Human", "Youngling", "Blue", "Clone Wars"]

    },
    {
        id: 66,
        imgSrc: 'images/Katooni.jpg',
        imgAlt: 'Katooni',
        name: 'Katooni',
        species: 'Tholothian',
        rank: 'Youngling',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Tholothian", "Youngling", "Blue", "Clone Wars"]

     
    },
    {
        id: 67,
        imgSrc: 'images/Byph.jpeg',
        imgAlt: 'Byph',
        name: 'Byph',
        species: 'Ithorian',
        rank: 'Youngling',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Ithorian", "Youngling", "Blue", "Clone Wars"]

    },
    {
        id: 68,
        imgSrc: 'images/Zatt.jpeg',
        imgAlt: 'Zatt',
        name: 'Zatt',
        species: 'Nautolan',
        rank: 'Youngling',
        lightsaber: 'green',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Nautolan", "Youngling", "Green", "Clone Wars"]


    },
    {
        id: 69,
        imgSrc: 'images/Gungi.jpeg',
        imgAlt: 'Gungi',
        name: 'Gungi',
        species: 'Wookie',
        rank: 'Youngling',
        lightsaber: 'green',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        tcw: 'The Clone Wars(2008-2020)',
        tbb: 'The Bad Batch(2021-2024)',
        tags: ["Wookie", "Youngling", "Green", "Clone Wars", "Order 66 Survivors"]

    },
    {
        id: 70,
        imgSrc: 'images/Ky_Narec.jpg',
        imgAlt: 'Ky Narec',
        name: 'Ky Narec',
        death: '23BBY, Rattatak',
        species: 'Human',
        padawan: 'Asajj Ventress',
        rank: 'Jedi Master',
        lightsaber: 'green',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Human", "Jedi Master", "Green"]

    },
    {
        id: 71,
        imgSrc: 'images/Pong_Krell.jpeg',
        imgAlt: 'Pong Krell',
        name: 'Pong Krell',
        death: '20BBY, Umbara',
        species: 'Besalisk',
        rank: 'Jedi Master',
        lightsaber: 'green, blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Besalisk", "Youngling", "Green", "Blue", "Clone Wars"]

    },
    {
        id: 72,
        imgSrc: 'images/Tutso_Mara.jpeg',
        imgAlt: 'Tutso Mara',
        name: 'Tutso Mara',
        death: '19BBY, Coruscant',
        species: 'Mirialan',
        master: 'Aayla Secura',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        war: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Mirialan", "Jedi Knight", "Blue", "Clone Wars"]

    },
    {
        id: 73,
        imgSrc: 'images/Thongla Jur.jpeg',
        imgAlt: 'Thongla Jur',
        name: 'Thongla Jur',
        species: 'Anx',
        rank: 'Jedi Master',
        lightsaber: 'green',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Anx", "Jedi Master", "Green", "Clone Wars"]

    },
    {
        id: 74,
        imgSrc: 'images/Coleman_Kcaj.JPG',
        imgAlt: 'Coleman Kcaj',
        name: 'Coleman Kcaj',
        death: '9BBY',
        species: 'Ongree',
        rank: 'Jedi Master',
        lightsaber: 'green',
        council: '19BBY, replaced Even Piell',
        survivor: 'Order 66 Survivor (19-9BBY)',
        tcw: 'The Clone Wars(2008-2020)',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Ongree", "Jedi Master", "Green", "Jedi High Council", "Clone Wars", "Order 66 Survivors"]

    },
    {
        id: 75,
        imgSrc: 'images/Tiplar.jpg',
        imgAlt: 'Tiplar',
        name: 'Tiplar',
        death: '19BBY, Ringo Linda',
        species: 'Mikkian',
        family: 'Family',
        siblings: 'Tiplee (twin)',
        rank: 'Jedi Master',
        lightsaber: 'green',
        wars: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Mikkian", "Jedi Master", "Green", "Clone Wars"]

    },
    {
        id: 76,
        imgSrc: 'images/Tiplee.jpg',
        imgAlt: 'Tiplee',
        name: 'Tiplee',
        species: 'Mikkian',
        family: 'Family',
        siblings: 'Tiplee (twin)',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        wars: 'Clone Wars',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Mikkian", "Jedi Master", "Blue", "Clone Wars"]
    },
    {
        id: 77,
        imgSrc: 'images/Rig_Nema.jpeg',
        imgAlt: 'Rig Nema',
        name: 'Rig Nema',
        death: '19BBY, Kaliida Shoals Medical Center',
        species: 'Halaisi',
        padawan: 'Mill Alibeth',
        rank:'Jedi Counslar Doctor',
        lightsaber: 'green',
        tcw: 'The Clone Wars(2008-2020)',
        tags: ["Halaisi", "Jedi Counsular Doctor", "Green", "Clone Wars"]
    },
    {
        id: 78,
        imgSrc: 'images/Cin_Drallig.jpg',
        imgAlt: 'Cin Drallig',
        name: 'Cin Drallig',
        death: '19BBY, Jedi Temple',
        species: 'Human',
        master: 'Yoda',
        rank: 'Jedi Master',
        lightsaber: 'green',
        tcw: 'The Clone Wars(2008-2020)',
        rojs: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Human", "Jedi Master", "Green", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 79,
        imgSrc: 'images/Whie.jpg',
        imgAlt: 'Whie Malreaux',
        name: 'Whie Malreaux',
        death: '19BBY, Jedi Temple',
        species: 'Human',
        master: 'Maks Leem',
        rank: 'Padawan',
        lightsaber: 'green',
        rojs: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Human", "Padawan", "Green", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 80,
        imgSrc: 'images/Bene.jpg',
        imgAlt: 'Bene',
        name: 'Bene',
        death: '19BBY, Jedi Temple',
        species: 'Human',
        rank: 'Padawan',
        lightsaber: 'blue',
        rojs: 'Star Wars III: Revenge of the Sith(2005)',
        tags: ["Human", "Padawan", "Blue", "Clone Wars", "Victim of Order 66"]
    },
    {
        id: 81,
        imgSrc: 'images/Grand_Inquisitor.png',
        imgAlt: 'Grand Inquisitor',
        name: 'Grand Inquisitor',
        species: "Pau'an",
        rank: 'Jedi Temple Guard',
        lightsaber: 'yellow',
        war: 'Clone Wars',
        suvivor: 'Order 66 Survivor',
        survivor_info: "He fell to the dark side before Order 66, because he felt disillusioned with the Jedi Order. He was then anointed as the Grand Inquisitor by Darth Sidious, the leader of the Empire's Jedi Hunters.",
        sith: 'Grand Inquisitor',
        swr: 'Star Wars Rebels(2014-2018)',
        owk: 'Obi-Wan Kenobi(2022)',
        tote: 'Tales of the Empire(2024)',
        tags: ["Pau'an", "Jedi Temple Guard", "Jedi Knight", "Yellow", "Red", "Clone Wars", "Order 66 Survivors", "Sith"]

    },

    {
        id: 82,
        imgSrc: 'images/4thSister.jpeg',
        imgAlt: 'Lyn Rakish',
        name: 'Lyn Rakish',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor',
        sith: '4th Sister',
        owk: 'Obi-Wan Kenobi(2022)',
        tote: 'Tales of the Empire(2024)',
        tags: ["Human", "Red", "Order 66 Survivors", "Sith"]
    },
    {
        id: 83,
        imgSrc: 'images/5thBrother.jpeg',
        imgAlt: 'Fifth Brother',
        name: 'Fifth Brother',
        death: '3BBY, Malachor',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor(19-3BBY)',
        sith: '5th Brother(19-3BBY)',
        swr: 'Star Wars Rebels(2014-2018)',
        owk: 'Obi-Wan Kenobi(2022)',
        tags: ["Human", "Red", "Order 66 Survivors", "Sith"]
    },
    {
        id: 84,
        imgSrc: 'images/7thSister.jpeg',
        imgAlt: 'Seventh Sister',
        name: 'Seventh Sister',
        death: '3BBY, Malachor',
        species: 'Mirialan',
        rank: 'Unknown',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor(19-3BBY)',
        sith: 'Seventh Sister(19-3BBY)',
        swr: 'Star Wars Rebels(2014-2018)',
        tags: ["Mirialan", "Red", "Order 66 Survivors", "Sith"]
    },
    {
        id: 85,
        imgSrc: 'images/8thBrother.jpeg',
        imgAlt: 'Eigheth Brother',
        name: 'Eigheth Brother',
        death: '3BBY, Malachor',
        species: 'Terrelian Jango Jumper',
        rank: 'Unknown',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor',
        sith: 'Eigheth Brother(19-3BBY)',
        swr: 'Star Wars Rebels(2014-2018)',
        tags: ["Terrelian Jango Jumper", "Red", "Order 66 Survivors", "Sith"]
    },
    {
        id: 86,
        imgSrc: 'images/Dante.jpeg',
        imgAlt: 'Dante',
        name: 'Dante',
        death: '19BBY, Nur',
        species: 'Caphex',
        rank: 'Unknown',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor',
        tote: 'Tales of the Empire(2024)',
        tags: ["Caphex", "Red", "Order 66 Survivors"]
    },

 
    {
        id: 87,
        imgSrc: 'images/Ahmar.jpeg',
        imgAlt: 'Ahmar',
        name: 'Ahmar',
        death: '19BBY, Nur',
        species: 'Unknown',
        rank: 'Unknown',
        survivor: 'Order 66 Survivor',
        tote: 'Tales of the Empire(2024)',
        tags: ['Order 66 Survivors']
    },
    {
        id: 88,
        imgSrc: 'images/Jarol_Tapal.jpeg',
        imgAlt: 'Jarol Tapal',
        name: 'Jarol Tapal',
        birth: '61BBY, Lasan',
        death: '19BBY, near Bracca',
        species: 'Lasat',
        master: 'Yaddle',
        padawan: 'Cal Kestis',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        tags: ["Lasat", "Jedi Master", "Blue", "Clone Wars", "Victim of Order 66"]

    },
    {
        id: 89,
        imgSrc: 'images/Cal_Kestis.jpg',
        imgAlt: 'Cal Kestis',
        name: 'Cal Kestis',
        birth: '32BBY',
        species: 'Human',
        master: 'Jarol Tapal, Cere Junda',
        rank: 'Padawan',
        lightsaber: 'blue',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor', 
        survivor_info: 'He ',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Human", "Padawan", "Blue", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 90,
        imgSrc: 'images/Eno_Cordova.jpeg',
        imgAlt: 'Eno Cordova',
        name: 'Eno Cordova',
        death: '9BBY, Jedha',
        species: 'Human',
        padawan: 'Cere Junda',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19-9BBY)',
        swjfo: 'Star Wars Jedi: Fallen Order',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Human", "Jedi Master", "Blue", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 91,
        imgSrc: 'images/Cere_Junda.jpeg',
        imgAlt: 'Cere Junda',
        name: 'Cere Junda',
        death: '9BBY, Jedha',
        species: 'Human',
        master: 'Eno Cordova',
        padawan: 'Trilla Sudiri, Cal Kestis',
        rank: 'Jedi Master',
        lightsaber: 'green',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19-9BBY)',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Human", "Jedi Master", "Green", "Blue", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 92,
        imgSrc: 'images/Trilla_Sudiri.jpg',
        imgAlt: 'Trilla Sudiri',
        name: 'Trilla Sudiri',
        death: '14BBY, Nurr',
        species: 'Human',
        master: 'Cere Junda',
        rank: 'Padawan',
        lightsaber: 'red',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19-14BBY)',
        sith: 'Second Sister(19-14BBY)',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        tags:["Human", "Jedi Master", "Red", "Clone Wars", "Order 66 Survivors", "Sith"]
    },
    {
        id: 93,
        imgSrc: 'images/9thSister.jpeg',
        imgAlt: 'Masana Tide',
        name: 'Manasa Tide',
        death: '9BBY, Coruscant',
        species: 'Dowutin',
        rank: 'Jedi Knight',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor(19-9BBY)',
        sith: 'Ninth Sister(19-9BBY)',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Dowutin", "Red", "Jedi Knight", "Order 66 Survivors", "Sith"]
    },
    {
        id: 94,
        imgSrc: 'images/Bode_Akuna.jpeg',
        imgAlt: 'Bode Akuna',
        name: 'Bode Akuna',
        death: '9BBY, Tanalorr',
        species: 'Human',
        family: 'Family',
        spouse: 'Tayala',
        children: 'Kata Akuna',
        rank: 'Jedi Knight',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor(19-9BBY)',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Human", "Red", "Jedi Knight", "Order 66 Survivors"]
    },
    {
        id: 95,
        imgSrc: 'images/Santari_Khri.jpeg',
        imgAlt: 'Santari Khri',
        name: 'Santari Khri',
        species: 'Human',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Human", "Blue", "Jedi Master", "High Republic"]
    },
    {
        id: 96,
        imgSrc: 'images/Dagan_Gera.jpeg',
        imgAlt: 'Dagan Gera',
        name: 'Dagan Gera',
        birth: '250-230BBY',
        death: '9BBY, Koboh',
        species: 'Arkanian Offshoot',
        rank: 'Jedi Knight',
        lightsaber: 'yellow',
        swjs: 'Star Wars Jedi: Survivor(2023)',
        tags: ["Arkanian Offshoot", "Yellow", "Jedi Knight", "High Republic"]
    },
    {
        id: 97,
        imgSrc: 'images/Taron_Malicos.jpeg',
        imgAlt: 'Taron Malicos',
        name: 'Taron Malicos',
        death: '14BBY, Dathomir',
        species: 'Human',
        rank: 'Jedi Master',
        lightsaber: 'red',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor',
        swjfo: 'Star Wars Jedi: Fallen Order(2019)',
        tags: ["Human",  "Red", "Jedi Master", "Clone Wars", "Order 66 Survivors"]
    },
    {
        id: 98,
        imgSrc: 'images/Rani.jpg',
        imgAlt: 'Rani',
        name: 'Rani',
        death: '9BBY, Tatooine',
        species: 'Human',
        rank: 'Jedi Knight',
        lightsaber: 'blue',
        survivor: 'Order 66 Survivor (19-9BBY)',
        owk: 'Obi-Wan Kenobi(2022)',
        tags: ["Human", "Jedi Knight", "Blue", "Order 66 Survivors"]

    },
    {
        id: 99,
        imgSrc: 'images/3rdSister.jpeg',
        imgAlt: 'Reva Sevander',
        name: 'Reva Sevander',
        birth: '31BBY',
        species: 'Human',
        master: 'Yoda, Darth Vader, The Grand Inquisitor',
        rank: 'Youngling',
        lightsaber: 'red',
        survivor: 'Order 66 Survivor',
        sith: 'Third Sister',
        owk: 'Obi-Wan Kenobi(2022)',
        tags: ["Human", "Red", "Youngling", "Order 66 Survivors", "Sith"]
    },
    {
        id: 100,
        imgSrc: 'images/Kanan_Jarrus.jpg',
        imgAlt: 'Kanan Jarrus',
        name: 'Kanan Jarrus',
        birth: '33BBY',
        death: '1BBY, Lothal',
        species: 'Human',
        family: 'Family',
        spouse: 'Hera Syndulla',
        children: 'Jacen Syndulla',
        master: 'Depa Billaba',
        padawan: 'Ezra Bridger, Sabine Wren',
        rank: 'Padawan, eventually Jedi Knight',
        lightsaber: 'blue',
        midochlorians: '14,000',
        war: 'Clone Wars',
        survivor: 'Order 66 Survivor(19-1BBY)',
        survivor_info: 'He was in Kaller with his master Depa Billaba during Order 66. When Order 66 was issued, Billaba sacrificed herself so her padawan could escape. He managed to survive because Clone Force 99, aka the Bad Batch, were able to resist their inhibitor chips.',
        alliance: "Rebel Alliance(5-1BBY)",
        tbb: 'The Bad Batch(2021-2024)',
        totj: 'Tales of the Jedi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        tags: ["Human", "Padawan", "Jedi Knight", "Blue", "Clone Wars", "Order 66 Survivors", "Rebel Alliance"]
    },
    {
        id: 101,
        imgSrc: 'images/Ezra_Bridger.jpeg',
        imgAlt: 'Ezra Bridger',
        name: 'Ezra Bridger',
        birth: 'Empire Day, 19BBY, Lothal',
        species: 'Human',
        family: 'Family',
        parents: 'Ephraim Brdger, Mira Bridger',
        master: 'Kanan Jarrus',
        rank: 'Padawan',
        lightsaber: 'blue',
        midochlorians: '10,000',
        alliance: "Rebel Alliance(5-1BBY)",
        swr: 'Star Wars Rebels(2014-2018)',
        ahsoka: 'Ahsoka(2023)',
        tags: ["Human", "Padawan", "Blue", "Green", "Rebel Alliance"]
    },
    {
        id: 102,
        imgSrc: 'images/Sabine_Wren.jpeg',
        imgAlt: 'Sabine Wren',
        name: 'Sabine Wren',
        birth: '21BBY, Mandalore',
        species: 'Human',
        family: 'Family',
        parents: 'Alrich Wren, Ursa Wren',
        siblings: 'Tristan Wren',
        master: 'Kanan Jarrus, Ahsoka Tano',
        rank: 'Unknown',
        lightsaber: 'green',
        alliance: 'Rebel Alliance',
        republic: 'New Republic',
        swr: 'Star Wars Rebels(2014-2018)',
        ahsoka: 'Ahsoka(2023)',
        tags: ["Human", "Green", "Rebel Alliance", "New Republic"]
    },
    {
        id: 103,
        imgSrc: 'images/Luke_Skywalker.jpg',
        imgAlt: 'Luke Skywalker',
        name: 'Luke Skywalker',
        birth: '19BBY, Polis Massa',
        death: '34ABY, Atch-To',
        species: 'Human',
        family: 'Family',
        parents: 'Anakin Skywalker, Padme Amidala',
        siblings: 'Leia Organa, Han Solo (brother-in-law)',
        uncleAunt: 'Owen Lars, Beru Lars',
        nephewNiece: 'Ben Solo',
        master: 'Obi-Wan Kenobi, Yoda',
        padawan: 'Leia Organa, Grogu, Ben Solo, Rey',
        rank: 'Jedi Knight/ Grand Master',
        lightsaber: 'green',
        midochlorians: '23,316',
        alliance: 'Rebel Alliance (0-5ABY)',
        republic: 'New Republic',
        newJediOrder: 'New Jedi Order',
        resistance: 'The Resistance',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        ahsoka: 'Ahsoka(2023)',
        owk: 'Obi-Wan Kenobi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',        
        anh: 'Star Wars IV: A New Hope(1977)',
        tesb: 'Star Wars V: The Empire Strikes Back(1980)',
        rotj: 'Star Wars VI: Return of the Jedi(1983)',
        mandalorian: 'The Mandalorian(2019-2023)',
        tbobf: 'The Book of Boba Fett(2021-2022)',
        tfa: 'Star Wars VII: The Force Awakens(2015)',
        tlj: 'Star Wars VIII: The Last Jedi(2017)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Human", "Jedi Knight", "Grand Master", "Green", "Rebel Alliance", "New Republic", "New Jedi Order", "The Resistance"]


    },
    {
        id: 104,
        imgSrc: 'images/Leia.jpeg',
        imgAlt: 'Leia Organa',
        name: 'Leia Skywalker Organa',
        birth: '19BBY, Polis Kloss',
        death: '35ABY, Ajan Kloss',
        species: 'Human',
        family: 'Family',
        parents: 'Anakin Skywalker, Padme Amidala',
        stepParents: 'Bail Organa, Brea Organa',
        spouse: 'Han Solo',
        children: 'Ben Solo',
        siblings: 'Luke Skywalker',
        uncleAunt: 'Owen Lars, Beru Lars',
        master: 'Luke Skywalker',
        padawan: 'Rey',
        rank: 'Unknown',
        lightsaber: 'blue',
        midochlorians: '24,240',
        alliance: 'Rebel Alliance',
        republic: 'New Republic',
        newJediOrder: 'New Jedi Order',
        resistance: 'The Resistance',
        rots: 'Star Wars III: Revenge of the Sith(2005)',
        owk: 'Obi-Wan Kenobi(2022)',
        swr: 'Star Wars Rebels(2014-2018)',
        ro: 'Rogue One: A Star Wars Story(2016)',
        anh: 'Star Wars IV: A New Hope(1977)',
        tesb: 'Star Wars V: The Empire Strikes Back(1980)',
        rotj: 'Star Wars VI: Return of the Jedi(1983)',
        tfa: 'Star Wars VII: The Force Awakens(2015)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Human", "Blue", "Rebel Alliance", "New Republic", "New Jedi Order", "The Resistance"]
    },

    {
        id: 105,
        imgSrc: 'images/Grogu.jpg',
        imgAlt: 'Grogu',
        name: 'Grogu',
        birth: '41BBY',
        species: 'Yoda Species',
        family: 'Family',
        parents: 'Din Djarin',
        master: 'Kelleran Beq, Luke Skywalker',
        rank: 'Youngling',
        survivor: 'Order 66 Survivor',
        republic: 'New Republic',
        newJediOrder: 'New Jedi Order',
        mandalorian: 'The Mandalorian(2019-2023)',
        tbobf: 'The Book of Boba Fett(2021-2022)',
        tags: ["Youngling", "Order 66 Survivors", "New Republic", "New Jedi Order"]
    },

    {
        id: 106,
        imgSrc: 'images/Kelleran_Beq.jpeg',
        imgAlt: 'Kelleran Beq',
        name: 'Kelleran Beq',
        species: 'Human',
        padawan: 'Grogu',
        rank: 'Jedi Master',
        lightsaber: 'green',
        survivor: 'Order 66 Survivor',
        mandalorian: 'Mandalorian(2019-2023)',
        tags: ["Human", "Jedi Master", "Green", "Order 66 Survivors"]
    },  
    
    {
        id: 107,
        imgSrc: 'images/Babylan_Skoll.jpg',
        imgAlt: 'Babylan Skoll',
        name: 'Babylan Skoll',
        species: 'Human',
        padawan: 'Shin Hati',
        rank: 'Jedi Knight',
        lightsaber: 'orange',
        survivor: 'Order 66 Survivor',
        ahsoka: 'Ahsoka(2023)',
        tags: ["Human", "Jedi Knight", "Orange", "Order 66 Survivors"]
    },

    {
        id: 108,
        imgSrc: 'images/Shin_Hati.jpg',
        imgAlt: 'Shin Hati',
        name: 'Shin Hati',
        birth: 'after the Jedi Purge, 19BBY',
        species: 'Human',
        master: 'Babylan Skoll',
        rank: 'Padawan',
        lightsaber: 'orange',
        ahsoka: 'Ahsoka(2023)',
        tags: ["Human", "Padawan", "Orange"]   
    },

    {
        id: 109, 
        imgSrc: 'images/Ben_Solo.jpeg',
        imgAlt: 'Ben Solo',
        name: 'Ben Solo',
        birth: '5ABY, Chandrilla',
        death: '35ABY, Exegol',
        species: 'Human',
        family: 'Family',
        parents: 'Han Solo, Leia Skywalker Organa',
        grandparents: 'Anakin Skywalker, Padme Amidala',
        uncleAunt: 'Luke Skywalker',
        master: 'Luke Skywalker, Snoke, Darth Sidious',        
        lightsaber: 'blue',
        midochlorians: '16,000-18,000',
        newJediOrder: 'New Jedi Order',
        sith: 'Kylo Ren',
        tfa: 'Star Wars VII: The Force Awakens(2015)',
        tlj: 'Star Wars VIII: The Last Jedi(2017)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Human", "Blue", "Red", "Sith", "New Jedi Order"]
    },

    {
        id: 110,
        imgSrc: 'images/Rey.jpeg',
        imgAlt: 'Rey',
        name: 'Rey',
        birth: '15ABY, Kyperkarn',
        species: 'Human',
        family: 'Family',
        parents: 'Dathan, Miramar',
        grandparents: 'Emperor Palpatine (Darth Sidious)',
        master: 'Luke Skywalker, Leia Skywalker Organa',
        lightsaber: 'yellow',
        midochlorians: '16,000-18,000',
        resistance: 'The Resistance',
        tfa: 'Star Wars VII: The Force Awakens(2015)',
        tlj: 'Star Wars VIII: The Last Jedi(2017)',
        ros: 'Star Wars IX: Rise of Skywalker(2019)',
        tags: ["Human", "Yellow", "Blue", "The Resistance"]
    },
    {
        id: 111,
        imgSrc: 'images/Sol.jpeg',
        imgAlt: 'Sol',
        name: 'Sol',
        death: '132BBY, Brendok',
        species: 'Human',
        padawan: 'Osha, Jecki Lon',
        rank: 'Jedi Master',
        lightsaber: 'blue',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Blue", "Jedi Master", "High Republic"]
    },
    {
        id: 112,
        imgSrc: 'images/Jecki_Lon.jpeg',
        imgAlt: 'Jecki Lon',
        name: 'Jecki Lon',
        birth: '150BBY',
        death: '132BBY, Khofar',
        species: 'Theelin-Human Hybrid',
        master: 'Sol',
        rank: 'Padawan',
        lightsaber: 'green',
        ta: 'The Acolyte(2024)',
        tags: ["Theelin-Human Hybrid", "Green", "Padawan", "High Republic"]
    },
    {
        id: 113,
        imgSrc: 'images/Yord_Fandar.jpeg',
        imgAlt: 'Yord Fandar',
        name: 'Yord Fandar',
        death: '132BBY, Khofar',
        species: 'Human',
        padawan: 'Tasi Lowa',
        rank: 'Jedi Knight',
        lightsaber: 'yellow',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Yellow", "Jedi Knight", "High Republic"]
    },
    {
        id: 114,
        imgSrc: 'images/Vernestra_Rwoh.jpeg',
        imgAlt: 'Vernestra Rwoh',
        name: 'Vernestra Rwoh',
        birth: '248BBY',
        species: 'Mirialan',
        master: 'Stellan Gios',
        padawan: 'Qimir, Imri Cantaros',
        rank: 'Jedi Master',
        lightsaber: 'purple',
        ta: 'The Acolyte(2024)',
        tags: ["Mirialan", "Purple", "Jedi Master", "High Republic"]        
    },
    {
        id: 115,
        imgSrc: 'images/Indara.jpeg',
        imgAlt: 'Indara',
        name: 'Indara',
        death: '132BBY, Ueda',
        species: 'Human',
        padawan: 'Torbin',
        rank: 'Jedi Master',
        lightsaber: 'green',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Green", "Jedi Master", "High Republic"]
    },
    {
        id: 116,
        imgSrc: 'images/Torbin.jpeg',
        imgAlt: 'Torbin',
        name: 'Torbin',
        death: '132BBY, Olega',
        species: 'Human',
        master: 'Indara',
        rank: 'Jedi Master',
        lightsaber: 'yellow',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Yellow", "Jedi Master", "High Republic"]
    },
    {
        id: 117,
        imgSrc: 'images/Kelnacca.jpeg',
        imgAlt: 'Kelnacca',
        name: 'Kelnacca',
        death: '132BBY, Khofar',
        species: 'Wookie',
        rank: 'Jedi Master',
        lightsaber: 'green',
        ta: 'The Acolyte(2024)',
        tags: ["Wookie", "Green", "Jedi Master", "High Republic"]
    },
    {
        id: 118,
        imgSrc: 'images/Osha.jpeg',
        imgAlt: 'Osha',
        name: 'Osha',
        birth: '156BBY',
        species: 'Human',
        family: 'Family',
        parents: 'Aniseya, Kori',
        siblings: 'Mae(twin)',
        master: 'Sol, Qimir',
        rank: 'Unknown',
        lightsaber: 'red',
        sith: 'Apprentice to Qimir',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Red", "Sith", "High Republic"]
    },
    {
        id: 119,
        imgSrc: 'images/Mae.jpeg',
        imgAlt: 'Mae',
        name: 'Mae',
        birth: '156BBY',
        species: 'Human',
        family: 'Family',
        parents: 'Aniseya, Kori',
        siblings: 'Osha(twin)',
        master: 'Qimir',
        sith: 'Sith Acolyte',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Sith", "High Republic"]
    },
    {
        id: 120,
        imgSrc: 'images/Qimir.jpeg',
        imgAlt: 'Qimir',
        name: 'Qimir',
        species: 'Human',
        master: 'vernestra Rwoh, Darth Plagueis',
        padawan: 'Osha, Mae',
        rank: 'Unknown',
        lightsaber: 'red',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Red", "Sith", "High Republic"]
        
    },
    {
        id: 121,
        imgSrc: 'images/Tasi_Lowa.jpeg',
        imgAlt: 'Tasi Lowa',
        name: 'Tasi Lowa',
        species: 'Zygerrian',
        master: 'Yord Fandar',
        rank: 'Unknown',
        ta: 'The Acolyte(2024)',
        tags: ["Zygerrian", "High Republic"]
    },
    {
        id: 122,
        imgSrc: 'images/Mog_Adana.jpeg',
        imgAlt: 'Mog Adana',
        name: 'Mog Adana',
        species: 'Human',
        rank: 'Padawan',
        ta: 'The Acolyte(2024)',
        tags: ["Human",  "Padawan", "High Republic"]
    },
    {
        id: 123, 
        imgSrc: 'images/Ithia_Paan.jpeg',
        imgAlt: 'Ithia Paan',
        name: 'Ithia Paan',
        death: '132BBY, Khofar',
        species: 'Kel Dor',
        rank: 'Unknown',
        lightsaber: 'green',
        ta: 'The Acolyte(2024)',
        tags: ["Kel Dor", "Green", "High Republic"]
    },
    {
        id: 124,
        imgSrc: 'images/HumanJedi3.jpeg',
        imgAlt: 'Unamed Human Jedi 1',
        name: 'Unamed Human Jedi 1',
        death: '132BBY, Khofar',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'green',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Green", "High Republic"]


    },
    {
        id: 126,
        imgSrc: 'images/FemaleJedi.jpeg',
        imgAlt: 'Unamed Human Jedi 2',
        name: 'Unamed Human Jedi 2',
        death: '132BBY, Khofar',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'blue',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Blue", "High Republic"]
    },
    {
        id: 125,
        imgSrc: 'images/HumanJedi4.jpeg',
        imgAlt: 'Unamed Human Jedi 3',
        name: 'Unamed Human Jedi 3',
        death: '132BBY, Khofar',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'yellow',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Yellow", "High Republic"]
        
    },
    {
        id: 127,
        imgSrc: 'images/HumanJedi2.jpeg',
        imgAlt: 'Unamed Human Jedi 4',
        name: 'Unamed Human Jedi 4',
        death: '132BBY, Khofar',
        species: 'Human',
        rank: 'Unknown',
        lightsaber: 'yellow',
        ta: 'The Acolyte(2024)',
        tags: ["Human", "Yellow", "High Republic"]   
    }
];